# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bq51bGOTtA3NwCK87y4jdn8SSm9MYuL1
"""

import pandas as pd
from pathlib import Path

files = ["sheet1.csv", "sheet2.csv"]
dfs = []
for f in files:
    p = Path(f)
    if not p.exists():
        raise FileNotFoundError(f"Tidak ditemukan: {f}")
    df = pd.read_csv(p)
    dfs.append(df)

df = pd.concat(dfs, ignore_index=True)

df.columns = [str(c).strip().upper() for c in df.columns]

df["TANGGAL_ASLI"] = df["TANGGAL"].astype(str)

df["TANGGAL_PARSED"] = pd.to_datetime(
    df["TANGGAL_ASLI"],
    format="%m/%d/%Y %H:%M:%S",
    errors="coerce",
)
df["TANGGAL_VALID"] = df["TANGGAL_PARSED"].notna()
df["TANGGAL_DATE"] = df["TANGGAL_PARSED"].dt.date

if "BULAN" in df.columns and "TAHUN" in df.columns:
    df["BULAN_ASLI"] = df["BULAN"]
    df["TAHUN_ASLI"] = df["TAHUN"]
    mask_valid = df["TANGGAL_VALID"]
    df.loc[mask_valid, "BULAN"] = df.loc[mask_valid, "TANGGAL_PARSED"].dt.month
    df.loc[mask_valid, "TAHUN"] = df.loc[mask_valid, "TANGGAL_PARSED"].dt.year

numeric_cols = ["CHANNEL", "BERAT_SATUAN", "JUMLAH", "BERAT_TOTAL"]
for col in numeric_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")

for col in df.select_dtypes(include=["object"]).columns:
    df[col] = df[col].astype(str).str.strip()

df.to_csv("penjualan_helped.csv", index=False)

df.head()

df["TANGGAL"] = df["TANGGAL_PARSED"].dt.strftime("%Y-%m-%d")

cols_to_drop = [
    "TANGGAL_ASLI",
    "TANGGAL_PARSED",
    "TANGGAL_VALID",
    "TANGGAL_DATE",
    "BULAN_ASLI",
    "TAHUN_ASLI",
]

cols_to_drop = [c for c in cols_to_drop if c in df.columns]
df = df.drop(columns=cols_to_drop)

df.to_csv("penjualan_clean.csv", index=False)

df.head()